
version: 0.2

phases:
  install:
    commands:
#      - "apt install unzip -y"
#      - "wget https://releases.hashicorp.com/terraform_1.3.5/terraform_1.3.5_linux_arm.zip"
#      - "unzip terraform_1.3.5_linux_arm.zip"
#      - "mv terraform /usr/local/bin/"
  
  
     - "apt install unzip -y"
     - "wget https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_linux_amd64.zip"
     - "unzip terraform_0.14.10_linux_amd64.zip"
     - "mv terraform /usr/local/bin/"
  
  pre_build:
    commands:
      - terraform init
  build:
    commands:
#       - terraform $TF_COMMAND -auto-approve
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on 'date'



